name: Bandit Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.14  # Use a specific Python version

      - name: Install Bandit with TOML support
        run: pip install bandit[toml]

      - name: Run Bandit
        run: bandit -c pyproject.toml -r . --severity-level high